### ISSUE TITLE
!message not working as expected?

### ISSUE THREAD

**Issue by Oelus** [KararTY/DiscordTwitchAnnouncer#12]
Changing the `!message` only modifies the contents of `settings.json`. And `data.json` stays the same... And it seems the bot reads from data.json for the message. So it doesn't change at all when announcing the message.
Hopefully that's made some sense.

**Comment by KararTY** [comment]
`settings.json` shouldn't be modified by the `!message` command.

Could you show this behavior happening? I can't reproduce.

![image](https://user-images.githubusercontent.com/13697809/63537293-b39e6c80-c515-11e9-8833-70ea918c4197.png)

**Comment by Oelus** [comment]
Will do some more testing and reopen if it is still a problem!
Thanks^^
