### ISSUE TITLE
401 OAuth Token İs Missing

### ISSUE THREAD

**Issue by SametKecici** [KararTY/DiscordTwitchAnnouncer#17]
{ error: 'Unauthorized',
  status: 401,
  message: 'OAuth token is missing' }

I get an error called help description

**Comment by SametKecici** [comment]
The problem was resolved when using the new version, but this time it doesn't throw an error, even though it doesn't give error.

**Comment by SametKecici** [comment]
I'm testing right now and it doesn't even throw half command,  test version v3

**Comment by KararTY** [comment]
Are you using a Discord Bot Token from https://discordapp.com/developers/applications/me/ ?
It seems that discord.js has dropped support for Discord User Tokens. You may need to register a bot.

And if you're upgrading from version 2 to version 3, please follow the upgrade procedure described here: https://github.com/KararTY/DiscordTwitchAnnouncer#updating-from-2x-to-3x

**Comment by SametKecici** [comment]
I'm sure I'm doing everything properly but I'm not throwing the broadcast notification sorry can you check

**Comment by KararTY** [comment]
Usually Twitch takes time to update the "LIVE", I just quickly tested it and it took 2 minutes for Twitch API to update their response.

![image](https://user-images.githubusercontent.com/13697809/82589216-194e8080-9b9c-11ea-8d6f-989efd91a43f.png)
![image](https://user-images.githubusercontent.com/13697809/82589268-29666000-9b9c-11ea-90a5-2398b2aa44d8.png)
Of course, the default polling rate is 61000 milliseconds so it might take at least 3 minutes if that's accounted to.

Polling rate can be changed in settings.js by changing the timer variable.

**Comment by SametKecici** [comment]
Yes, I have not tried this, thank you mate, you should continue to develop very good software and I want something from you, it would be nice to throw the channel profile photo as a broadcast notification. thanks again

**Comment by KararTY** [comment]
> Yes, I have not tried this, thank you mate, you should continue to develop very good software and I want something from you, it would be nice to throw the channel profile photo as a broadcast notification. thanks again

If you could please open up a new issue for this feature request and show me a screenshot of what it may look like I'd appreciate it.
