### ISSUE TITLE
Feature request, i18n implementation

### ISSUE THREAD

**Issue by KararTY** [KararTY/DiscordTwitchAnnouncer#18]
Allow people to change the language of the bot.

**Comment by SametKecici** [comment]
turkish can be added i help

**Comment by KararTY** [comment]
@SametKecici Feel free to make a [pull request](https://github.com/KararTY/DiscordTwitchAnnouncer/pulls) for turkish support.

**Comment by SametKecici** [comment]
I started translation :)

Karar Al-Remahy <notifications@github.com>, 23 May 2020 Cmt, 09:14
tarihinde şunu yazdı:
