### ISSUE TITLE
Make the bot fetch the thumbnail then upload it to discord

### ISSUE THREAD

**Issue by Oelus** [KararTY/DiscordTwitchAnnouncer#2]
Make the bot fetch the thumbnail then upload it to discord. Then use that image URL in the embed so when looking back in announcements it's more relevant to what was happening in that stream. 

*Also prevents the caching problem where it shows an old thumbnail*

**Comment by KararTY** [comment]
Thanks for the request, added with V2.5.

**Comment by Oelus** [comment]
Thank you for maintaining this project so well 👍
