### ISSUE TITLE
2 lists, two channels

### ISSUE THREAD

**Issue by papy-frey** [KararTY/DiscordTwitchAnnouncer#24]
Hello, would it be possible to have 2 lists of streamers for 2 different shows?
For example, a list for the main streamer with his channel, and a list for the streamer's friends with a channel for them.

**Comment by KararTY** [comment]
Hey there, I've pushed commit 4728b00 that should allow you to do that.
Command: `!announcementchannel Streamer_Name #announcement-channel-2`

Please test it out and report any bugs you find!

**Comment by KararTY** [comment]
Unless there's new developments with the implemented feature, I'll be closing this issue on Friday.

Thank you for suggesting it!
