### ISSUE TITLE
!help does not work for members

### ISSUE THREAD

**Issue by AidinShkari** [KararTY/DiscordTwitchAnnouncer#28]
!help does not work for membes currect

**Comment by KararTY** [comment]
Yes, that's correct. It doesn't work for "normal" members because the commands are supposed to be used to set things up.

You can enable the bot to be used by some individuals or by roles/people who have a certain [permission](https://discord.com/developers/docs/topics/permissions).

**Comment by KararTY** [comment]
Please comment on this issue again if you require more help.

Thank you.
