### ISSUE TITLE
Option for owner in settings.js file

### ISSUE THREAD

**Issue by Oelus** [KararTY/DiscordTwitchAnnouncer#3]
Option to allocate & only allow a specific user to control the bot.
There should be an option in settings.js to specify a user

**Comment by KararTY** [comment]
Is it fine if the resulting feature can ONLY be changed by server's owner?

Or is the request a self-bot feature?

**Comment by Oelus** [comment]
I think it'd be more useful if you just allowed owners to be set in the settings.js file with a userID
In my case i'm not the owner of the server, but I run the announcement bot for a streamer, and to keep things simple for both of us and anyone else in a similar situation. It's better to explicitly set the bot owner/operator in the config imo.

But I think what you said would work fine too, up to you how you wish to implement it, I just think it's just something necessary to prevent random people from interacting with the bot without having to restrict the bot to one channel where no one has permission to send messages.

**Comment by Oelus** [comment]
Thinking over this again, what you said should be fine, assuming that the person running the bot can also add themselves manually with userID to the file which stores the bot operators.

**Comment by KararTY** [comment]
Alright, it's been added to V2.5.5
`!operator @User_Name`*
* Do note that only the server owner can add/remove operators. As a bot owner you can do too, if you were to access the `data.json` and add the ID's under the operator array for the guild.

I haven't thoroughly tested this, so open up a new issue if you find problems.

**Comment by KararTY** [comment]
And yes, permissionForCommand is supposed to prevent anyone but those who have the permission inside `settings.js`.

**Comment by Oelus** [comment]
Just confirming, are you able to set `permissionForCommands` to `NONE` to only allow the people who've been explicitly set as an operator to control the bot?

**Comment by KararTY** [comment]
If you add operators, `permissionForCommands` will be overridden.

If all operators are removed from the list, `permissionsForCommands` will work again.

You can delete someone by having server owner do `!operator @User_Name` again, as it's a toggle.

**Comment by Oelus** [comment]
Does this also support role ID's?

**Comment by KararTY** [comment]
It doesn't, make a new issue and I'll look into it.
