### ISSUE TITLE
Name (A-Z)

### ISSUE THREAD

**Issue by DarkZo0m** [KararTY/DiscordTwitchAnnouncer#46]
When Name is contain character like $%!%!@,. Bot Crashes !

**Comment by KararTY** [comment]
I'm sorry, what name?

**Comment by DarkZo0m** [comment]
for example:

!add h9881,19a.

it should be (A-Z,0-9)

**Comment by DarkZo0m** [comment]
It will crash but in read datas

**Comment by KararTY** [comment]
I'm not getting any crashes.
![image](https://user-images.githubusercontent.com/13697809/160252619-7a5d2f21-5ed1-487e-a4db-5f79324ab414.png)

**Comment by DarkZo0m** [comment]
Try this aliii,,,×£

**Comment by DarkZo0m** [comment]
Ow Ok 😊

**Comment by KararTY** [comment]
I'll push an update regardless, to newer Discord.js and with some features that were requested.

**Comment by KararTY** [comment]
Updated to newer discord.js in 817f85faccbc9ffbc22e705b246c3fe3e848aec5

Run `npm i` after dragging over the new files.

**Comment by KararTY** [comment]
This should've been fixed in f72dafe9fc3d85303bcf4bcb344e82833f579195 please make sure you've updated your copy of DTA.
