### ISSUE TITLE
update

### ISSUE THREAD

**Issue by Peppuss** [KararTY/DiscordTwitchAnnouncer#48]
I started the bot and work.. he says `Logged into Discord.
Activity has been set. [LISTENING] Twitch API.`

But when i type !help for a list command
`/home/peppe/Scrivania/DiscordTwitchAnnouncer-master/app.js:811
    } else if (message.member.hasPermission((settings.discord.permissionForCommands || 'MANAGE_ROLES'), false, true, true)) {
                              ^

TypeError: message.member.hasPermission is not a function
    at Client.<anonymous> (/home/peppe/Scrivania/DiscordTwitchAnnouncer-master/app.js:811:31)
    at Client.emit (node:events:526:28)
    at MessageCreateAction.handle (/home/peppe/Scrivania/DiscordTwitchAnnouncer-master/node_modules/discord.js/src/client/actions/MessageCreate.js:26:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/peppe/Scrivania/DiscordTwitchAnnouncer-master/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/peppe/Scrivania/DiscordTwitchAnnouncer-master/node_modules/discord.js/src/client/websocket/WebSocketManager.js:351:31)
    at WebSocketShard.onPacket (/home/peppe/Scrivania/DiscordTwitchAnnouncer-master/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/home/peppe/Scrivania/DiscordTwitchAnnouncer-master/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/home/peppe/Scrivania/DiscordTwitchAnnouncer-master/node_modules/discord.js/node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (node:events:526:28)
    at Receiver.receiverOnMessage (/home/peppe/Scrivania/DiscordTwitchAnnouncer-master/node_modules/discord.js/node_modules/ws/lib/websocket.js:1137:20)`

Some of my friend says me because it for old node... idk, can u help me?

**Comment by Peppuss** [comment]
https://imgur.com/a/J3isriB

**Comment by KararTY** [comment]
Thanks for reporting this issue. This is now fixed in a993b3e48d78c655d463231af71a66eb8fc9e4b2.

Please test the new change and report back. Thank you.

**Breaking change:**
Operators can now work alongside the setting `permissionForCommands`. You can unset `permissionForCommands` to have only operators work.

**Comment by Peppuss** [comment]
if (message.guild && message.member) {
    // If message comes from a guild and guild member.
    if (data.guilds[message.guild.id].operator && data.guilds[message.guild.id].operator.length > 0) {
      // If server has operators set.
      if (data.guilds[message.guild.id].operator.includes(message.author.id)) {
        // If message is from an operator.
        allow = true
      } else if (message.author.id === message.guild.ownerId) {
        // Or from server owner.
        allow = true
      }
    } else if (message.member.hasPermission((settings.discord.permissionForCommands || 'MANAGE_ROLES'), false, true, true)) {
   }

    if (settings.discord.permissionForCommands && settings.discord.permissionForCommands.length > 0) {
      if (message.member.permissions.has(settings.discord.permissionForCommands || 'MANAGE_ROLES')) {
        // If message from a guild member with the required permission.
        allow = true
      } else if (!message.author.bot && (message.author.id === client.user.id)) {
        // If from myself (aka self-bot) in a guild.
        allow = true
      }
    }
  }
  
  if (allow) {
     const cleanedMessage = message.content.replace(new RegExp(`^<@${client.user.id}> `), data.guilds[message.guild.id].prefix || '!')
    if (message.cleanContent.startsWith(data.guilds[message.guild.id].prefix || '!') || message.mentions.users.find(u => u.id === client.user.id)) {
      const command = commands(translateDefault(data.guilds[message.guild.id].language)).find(command => command.commandNames.indexOf(cleanedMessage.split(/[ ]+/)[0].toLowerCase().substr(data.guilds[message.guild.id].prefix.length)) > -1)
      if (!command) return
 
      const handled = await command.handler(new Message(message))
      if (typeof handled === 'boolean' && handled === false) message.reply(command.showHelpText(new Message(message)))
    }
  }
})
 
client.on('guildCreate', guild => {
  if (!data.guilds[guild.id]) {
    cache.guilds[guild.id] = []
    saveData([{ guild: guild.id, action: 'addGuild' }])
    console.log(translate.addedGuild)
  }
})
 
 
 
 I SEND YOU FROM 801 TO 844, is correct? because it says the same thing

**Comment by Peppuss** [comment]
https://pastebin.com/kfMiBShU7

Look this, is better

**Comment by KararTY** [comment]
Replace your entire app.js with the new updated file.

https://raw.githubusercontent.com/KararTY/DiscordTwitchAnnouncer/master/app.js

**Comment by Peppuss** [comment]
Ok work, thx u so much, u're good

**Comment by Peppuss** [comment]
Something happened with your Twitch request: Cannot read properties of undefined (reading 'length')

When i add a streamer

**Comment by Peppuss** [comment]
LOG: 

`Using existing token. Token expires on Thu, 01 Jan 1970 00:00:00 GMT.
Client ID missmatched with Twitch token secret, refreshing token!
Invalid response, refreshing token!
Wrote token to disk. NOTE: DO NOT SHARE token.json WITH ANYONE.`

**Comment by KararTY** [comment]
> LOG: 
> 
> `Using existing token. Token expires on Thu, 01 Jan 1970 00:00:00 GMT.
Client ID missmatched with Twitch token secret, refreshing token!
Invalid response, refreshing token!
Wrote token to disk. NOTE: DO NOT SHARE token.json WITH ANYONE.`

That's fine.

**Comment by KararTY** [comment]
> Something happened with your Twitch request: Cannot read properties of undefined (reading 'length')
> 
> When i add a streamer it says this

Do you know what the name of the streamer is?

**Comment by Peppuss** [comment]
Yo, but the bot not send the message live, nothing in cmd

**Comment by KararTY** [comment]
> I restarted the bot and work, but the bot not send the message live, nothing in cmd

It updates every 1 minute. Depending on the settings.js "timer" entry. 61000 = 61 seconds.

**Comment by Peppuss** [comment]
Ok work, thx u so much, u can close
