### ISSUE TITLE
Add ability for bot to automatically post reactions once an announcement has been sent

### ISSUE THREAD

**Issue by Oelus** [KararTY/DiscordTwitchAnnouncer#5]
Add ability for bot to automatically post reactions once an announcement has been sent.
Something that's not neccessary, but I find would be a cool addition to the bot

**Comment by KararTY** [comment]
Going to have to be more specific, reactions where?

**Comment by Oelus** [comment]
Reactions under the message of announcement
Whereby you can configure these emotes in the settings.js with the emoteID

![image](https://user-images.githubusercontent.com/20266745/53356127-9ef46980-3922-11e9-807c-480a7ee9c15a.png)

**Comment by KararTY** [comment]
I'll add this when I get time only alongside other more important feature requests if any were to be requested. But for now, I won't add it.

**Comment by KararTY** [comment]
For anyone looking at the label, feel free to make a pull request.

**Comment by Oelus** [comment]
Understandable, that's fine 👍

**Comment by KararTY** [comment]
Reactions has now been implemented via command `!reaction`.
