### ISSUE TITLE
fetch error etimedout

### ISSUE THREAD

**Issue by Giulius87** [KararTY/DiscordTwitchAnnouncer#50]
hello,
I'm getting these errors sometimes and the bot is unable to announce the streaming or in the "best case" is delayed (between 5 to even 40 minutes).
Initially I thought the problem was the host, but even after change it these errors still appears sporadically.
Do you have any clues/suggestions on how to solve it?

![error](https://user-images.githubusercontent.com/115401445/194752428-5d33a24b-bf86-450f-b714-386b2327c618.png)

**Comment by KararTY** [comment]
Hi, thanks for the report. I'll try my best to help you.

Can you give me more details? What Node.js version are you on and what DiscordTwitchAnnouncer commit is this?

**Comment by Giulius87** [comment]
On the old host there were only two choices: 16.6 and 16.9, on the new host there is Node 16, 17 and 18 (don't know exactly which version because isn't specified); I did the test with all of them and there is no difference, I always have those errors.
About the commit, I'm using the latest available.
I also tried to create a new Twitch application with a new client ID and secret and a new Discord token, but still the same.

**Comment by KararTY** [comment]
I'll take a look at it this coming weekend, might be a node-fetch issue or Twitch deprecations that I've forgotten about. Thanks for reporting it.

**Comment by KararTY** [comment]
Could you try out the new version and report back?
Also, make sure your timer is set to a sensible value, like 1 minute `60000`.

**Comment by Giulius87** [comment]
ok I'll wipe everything on one of the my two host, set it up again from scratch, set the timer at 60000 ms, try for few days and let you know.

**Comment by Giulius87** [comment]
after some days of testing I can say it works like a charm with no errors at all, thank you!

**Comment by Giulius87** [comment]
just a couple of off-topic questions:
- would be possible to re-introduce the bot status (watching/playing/streaming)?
- would be useful if the bot can generates a log.txt file with date and time of any actions/errors, so in case of malfunction we can attach that file; is it something feasible?

**Comment by KararTY** [comment]
> just a couple of off-topic questions:
> 
> * would be possible to re-introduce the bot status (watching/playing/streaming)?
> * would be useful if the bot can generates a log.txt file with date and time of any actions/errors, so in case of malfunction we can attach that file; is it something feasible?

**Please create a separate issue for both of these to make it easier for me to follow-up.**

**Comment by KararTY** [comment]
> after some days of testing I can say it works like a charm with no errors at all, thank you!

I'm happy to hear, I'll take a look at your two other issues during the weekend. Thank you for using DTA.
