### ISSUE TITLE
Feature suggestion: log file for easy report

### ISSUE THREAD

**Issue by Giulius87** [KararTY/DiscordTwitchAnnouncer#53]
would be useful if the bot can generates a *log.txt* file with date and time of any actions and errors, so in case of malfunction we can attach that file and report here; is it something feasible?

**Comment by KararTY** [comment]
I'll consider this, for now I recommend running the bot on PM2 which will log all errors to a file.

**Comment by KararTY** [comment]
While PM2 may be enough for catching errors, I've gone ahead and added a data.json logger in #54.
