### ISSUE TITLE
bot doesn't start

### ISSUE THREAD

**Issue by Giulius87** [KararTY/DiscordTwitchAnnouncer#55]
Hello again,
I downloaded the bot from scratch using the latest commit and setup using node 16.9 (any previous version I got a warning error), but the bot doesn't want to start for some reason. 
Of course I edited the setting.cjs file with the proper token and IDs

<img width="985" alt="Schermata 2022-10-23 alle 13 42 51" src="https://user-images.githubusercontent.com/115401445/197387820-ad3e2605-25f7-4b54-9ed7-c331d81b9965.png">

**Comment by KararTY** [comment]
Requirement is LTS, which right now is 16.18, with the lowest one I tested being 16.14. You can ignore that error, but otherwise it works for me on 16.14.2

**Comment by Giulius87** [comment]
oh ok, I have to try the other host because the one I posted the pic has 16.9 as most recent version so maybe will never going to work

**Comment by KararTY** [comment]
> oh ok, I have to try the other host because the one I posted the pic has 16.9 as most recent version so maybe will never going to work

What about Node 17 or 18? Is 16 the only one they have?

**Comment by Giulius87** [comment]
they have older versions as well (15, 14, 12 and 10) but not newer. I already contact their support service asking if would be possible to have also (at least) the LTS version, but I'm still waiting for an answer.
the other host I remember have 16, 17 and 18 available so in the meantime I'll use that one once I'll finish to configure

**Comment by Giulius87** [comment]
ok after one day I confirm that with the other host (having and using Nodejs 17 image repository) works perfectly.
thank you again for the help, this case can be close.
