### ISSUE TITLE
Command to check the bots uptime

### ISSUE THREAD

**Issue by Oelus** [KararTY/DiscordTwitchAnnouncer#6]
Be able to check the uptime of the bot, and possibly the ping too.
Useful to know when the bot goes offline without having to ssh into the server to check pm2 etc
Just something that would be a nice addition
Thanks

**Comment by KararTY** [comment]
That shouldn't be hard to implement. But doing `!help` should tell you whether it's offline or online, for now.

**Comment by KararTY** [comment]
`!uptime` has been implemented.
