### ISSUE TITLE
Create an option to specify the timezone displayed

### ISSUE THREAD

**Issue by Oelus** [KararTY/DiscordTwitchAnnouncer#8]
Option to specify timezone displayed...
![image](https://user-images.githubusercontent.com/20266745/61999487-e2155d00-b0b9-11e9-96ad-ec1e630cfde6.png)
![image](https://user-images.githubusercontent.com/20266745/61999493-f2c5d300-b0b9-11e9-94de-6a2276513947.png)

**Comment by KararTY** [comment]
`!timezone en-US America/New_York` is now implemented.

**Comment by KararTY** [comment]
Make sure you run `npm install` again to download the new npm modules as I'm now using `moment-timezone` for this feature.
