### ISSUE TITLE
prefix issue

### ISSUE THREAD

**Issue by k1ck3r** [KararTY/DiscordTwitchAnnouncer#9]
Hello,

first of all thank you for this easy-mode announcer ;) the issue i'm having is that no matter what prefix is used (eg: = or ! or ~) all commands work. Could you be so kind to provide information how can the prefix be controlled - even better how can be controlled for every other channel which the bot is listening to.

Thank you in advance

**Comment by KararTY** [comment]
Thanks a lot for the report!

Per feedback, I've also added a command to change the prefix, and made it so you can @ the bot now too instead of using the prefix!

**Comment by k1ck3r** [comment]
awesome mate, thanks for your attention. closing the issue, but will suggest to make the help text embed, instead of plain - would be also awesome and kinky of course :")) thanks one more time
